### ISSUE TITLE
Last item in View menu is duplicated under OS2, but not under AOS

### ISSUE THREAD

**Issue by mrwarper** [komh/vlc-os2#18] opened 2019-11-08 12:19 UTC
Because of issue #17, I have started to compare behaviour of the same VLC copy under different OS installations, and I bumped into this:

The last menu item under menu "View", called "VLSub" appears twice when running under OS2. I thought this might be normal, but running VLC under a fresh ArcaOS 5.0.4.3, "VLSub" only appears once.

Again, this may be because my main OS2 system was manually cobbled together and it is showing its age in places. If you think this is the case, please state so and I will dismiss this.

**Comment by mrwarper** [comment] 2019-11-08 12:20
![VLC@OS2](https://user-images.githubusercontent.com/866343/68476219-68e5e400-022a-11ea-8d7b-77cb8a14aaf5.png)

![VLC@AOS](https://user-images.githubusercontent.com/866343/68476238-77340000-022a-11ea-8a62-26ec36e329fb.png)

**Comment by dspiatkowski** [comment] 2019-11-08 14:29
On Fri, 08 Nov 2019 04:19:03 -0800 mrwarper wrote:
> Because of issue #17, I have started to compare behaviour of the same VLC  
> copy under
> different OS installations, and I bumped into this:
>
> The last menu item under menu "View", called "VLSub" appears twice when  
> running under OS2. I
> thought this might be normal, but running VLC under a fresh ArcaOS  
> 5.0.4.3, "VLSub" only
> appears once.
>
> Again, this may be because my main OS2 system was manually cobbled  
> together and it is
> showing its age in places. If you think this is the case, please state so  
> and I will dismiss this.

I've got VLC 3.0.9 here along with SNAP 505 (which is a AN build). No  
problem, single menu item 'VLSub'.

-Dariusz

**Comment by komh** [comment] 2019-11-08 15:16
@mrwarper I cannot reproduce it here.

However, I think, duplicated files of VLSub.luac may exist. 

And maybe did you install new VLC build over old VLC build ?

**Comment by mrwarper** [comment] 2019-11-08 15:57
On 2019/11/08 16:16, KO Myung-Hun wrote:
> @mrwarper <https://github.com/mrwarper> I cannot reproduce it here.

:(

> However, I think, duplicated files of VLSub.luac may exist.
>
> And maybe did you install new VLC build over old VLC build ?

No, I always install new versions in new directories, i.e. I had 
D:\MMedia\vlc308, D:\MMedia\vlc306, etc.

Also, there are no duplicate vlsub.luac files left over or otherwise (I 
checked just in case). If there were, they would show up when booting from 
ArcaOS as well.

Just to clarify, I normally work on OS/2 (MCP2/es, booting from C:), but when 
I test stuff under ArcaOS (booting from X:), I don't install new copies of 
programs if I can just execute them where they all live, on D:.

Thank you anyway,
AFD.

**Comment by komh** [comment] 2019-11-10 23:25
Please set HOME env. var. to an other directory for test, and confirm LIBPATH for VLC.

**Comment by komh** [comment] 2019-11-14 12:35
In your log in #17, 

> lua debug: Opening Lua Extension module
> lua debug: Trying Lua scripts in D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions
> lua debug: Trying Lua playlist script D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions\VLSub.luac
> lua debug: Scanning Lua script D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions\VLSub.luac
> lua debug: Script D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions\VLSub.luac has the following capability flags: 0x5
> lua debug: Trying Lua scripts in D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions
> lua debug: Trying Lua playlist script D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions\VLSub.luac
> lua debug: Scanning Lua script D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions\VLSub.luac
> lua debug: Script D:\MMEDIA\VLC308\USR\LOCAL\LIB\vlc\lua\extensions\VLSub.luac has the following capability flags: 0x5

VLSub.luac is scanned twice in the same directory.

Extensions directory is scaned in following order:

1. lua/extensions of %HOME% or /vlc2/usr/local/lib/vlc if %HOME% not defined
2. lua/extensions of /vlc2/usr/local/lib/vlc
3. lua/extensions of %VLC_DATA_PATH% or /vlc2/usr/local/share if %VLC_DATA_PATH% not defined

Please check them.

**Comment by mrwarper** [comment] 2019-11-15 10:17
Hi KO, sorry for the delay...

El 19/11/14 13:35, KO Myung-Hun escribi??:
> In your log in #17 <https://github.com/komh/vlc-os2/issues/17>,
[...]
> VLSub.luac is scanned twice in the same directory.
>
> Extensions directory is scaned in following order:
>
>  1. lua/extensions of %HOME% or /vlc2/usr/local/lib/vlc if %HOME% not defined
>  2. lua/extensions of /vlc2/usr/local/lib/vlc
>  3. lua/extensions of %VLC_DATA_PATH% or /vlc2/usr/local/share if
>     %VLC_DATA_PATH% not defined
>
> Please check them.

Dag nabbit!

The problem seems to be something unset my %HOME% to NULL at some point, 
indeed. (My test install of AOS to X: is suspect #1 because it is known to 
have caused other problems in C:, but I have no way to tell for sure now.)

Anyway, after setting %HOME% back to "D:\Home", the duplicate item is gone -- 
"problem" solved ^^

**Comment by komh** [comment] 2019-11-15 12:33
Good! Close this ticket. ^^

**Closed by komh** 2019-11-15 12:33 UTC
Labels: question, resolved
